### ISSUE TITLE
should we include prevalence results?

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/THIN_incidence_prevalence_colorectal_cancer#18]
@daniprietoalhambra due to the quirkyness of the the THIN databases and they are not capturing mortality - this is giving us differences between prevalence between GOLD and THIN databases as well as other issues such as mapping from source > THIN CDM > OMOP cdm - so should we even include it in this paper and just focus on some nice characterisation and incidence rates?

**Comment by daniprietoalhambra** [comment]
I would not do mortality for the THIN analyses. Is that what you mean?

**Comment by daniellenewby** [comment]
So yes wouldnt do surival either - prevalence is keeping people in that might have died as we dont know if they have died or not so is inflating prevalence (we saw it in Rabia's breast cancer study she presented on friday)

**Comment by daniprietoalhambra** [comment]
Got you. So what you are suggesting is that we just focus on incidence and baseline characterisation, right? Happy with that too, you make the final decision for these ones

**Comment by daniellenewby** [comment]
correct :) and do it in more detailed and better with the matched characteristics etc ok.. will drop it :)
